### ISSUE TITLE
(Posts) Share That -- Links broken

### ISSUE THREAD

**Issue by nitya** [GDG-NewYork/devfest-nyc-2016#28]
Each post gets a Share That link -- twitter share works, others don't.

Short term -- remove all share links other than twitter.

Long term -- let's fix shares.

![screen shot 2016-10-24 at 2 41 25 pm](https://cloud.githubusercontent.com/assets/279083/19658950/f806ef56-99f7-11e6-965d-1f28fea6b38c.png)

**Comment by gautamarora** [comment]
@nitya looks like this is a bug with the df site. the blog post pages are failing (404ing) on G+ and FB because going directly to a deep link page results in a 404 (you can try in chrome incognito using a link like this https://devfestnyc.com/blog/posts/devfest-golang-training/)

I will proceed with removing the FB and G+ shares.

**Comment by gautamarora** [comment]
Fixed https://github.com/GDG-NewYork/devfest-nyc-2016/commit/2869343d215f82c1387242186c38deee05a86825
